// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzbvqkcmdekfuckrbjai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6YnZxa2NtZGVrZnVja3JiamFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzM2OTksImV4cCI6MjA3NDMwOTY5OX0._8sQ0NOd5KvhJxXwU7NYcfp20gF46S_AORDF6vD4N5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});